### ISSUE TITLE
Part mismatch between instruction PDF and DXF file

### ISSUE THREAD

**Issue by alexcg1** [wikihouseproject/Microhouse#11]
DXF file: Microhouse_WRENchassis_v0.5.dxf
PDF file: MicroHouse_AssemblyManual_v1_sm.pdf

Trying to make a small sample section of Wikihouse and turns out the part labels in the instructions are different to the DXF.

For example:
* In the PDF, R2 has no "crucifix" cut into it and an obtuse angle. In the DXF, FRA-A/R2 has a crucifix and has a 90 degree angle. It's just a reversed FRA-A/R1
* In PDF, R3 has a notch on one side. In DXF, FRA-A/R3 has notch on the other side

I'm guessing it's not the parts themselves that are wrong, but the labels. From looking at the pieces themselves:
* PDF R2 == DXF FRA-A/R3
* PDF R3 == DXF FRA-A/R4

Can anyone else confirm?

[MicroHouse_AssemblyManual_v1_sm.pdf](https://github.com/wikihouseproject/Microhouse/files/969686/MicroHouse_AssemblyManual_v1_sm.pdf)

**Comment by HarryKnight** [comment]
@claytonprest would be best to confirm this.

**Comment by claytonprest** [comment]
Hi @alexcg1 Thanks for spotting this! Like you say, it's just a mismatch in labels.

I've corrected the assembly manual to match the DXF cutting files now. You can find the latest version here: https://github.com/wikihouseproject/Microhouse/blob/master/MicroHouse_AssemblyManual_v1_sm.pdf
