### ISSUE TITLE
Possible minor issues with Microhouse_WRENchassis_v0.5.dxf

### ISSUE THREAD

**Issue by skovholt** [wikihouseproject/Microhouse#7]
Hi,

looking closely at the dxf there seems to be a gap between the connection points in frame (between FRA-A/F6 and FRA-A/F1), it's quite small so I suppose it doesn't pose any problem (see picture). Also FRA-A/S10/IN as well as FRA-A/S10/EX seems to be absent in the dxf? Also there are no pegs in that DXF, or MicroHouse_othercomponents_v0.5.dxf as far as I can tell (if the kind pictured should be used with this design?).

![image](https://cloud.githubusercontent.com/assets/8075211/22979677/7b79584e-f397-11e6-9627-741a8d60fe72.png)

![image](https://cloud.githubusercontent.com/assets/8075211/22979747/b96ac048-f397-11e6-98ee-1bb6af206141.png)

We plan to make a section of the Microhouse in Norway for an educational project (using 18mm OSB), are there any other things one should be aware of using Microhouse_WRENchassis_v0.5.dxf for cnc-cutting?

**Comment by claytonprest** [comment]
Hi @skovholt 
Thanks for raising these. I've had look at the DXF in regards to your queries.

1. There should be a gap of 0.75mm between FRA-A/F6 and FRA-A/F1. This is an offset of the original outline to create some tolerance for the assembly. Are you getting a gap any bigger than that?

2. I realise this is an error in the microhouse_0.5_chassis.skp sketchup model. If you refer to the Assembly Guide in this repo you'll see there shouldn't be any FRA-A/S10/IN or FRA-A/S10/EX parts. So the DXF cutting file is correct, and so I have updated the sketchup model now to match. 

3. Good question on the pegs. No these pegs are no longer part of the latest WREN system and aren't required in the design. So hopefully there should be less fiddly parts.

Sounds exciting. Will just be building the chassis for your project? If you're looking at finishes and cladding you can download the Engine spreadsheet there's a good spec of others materials and approximate costs. We're currently doing some development on the gable end wall system of the chassis, so those elements will hopefully be updated in the next few weeks.

Let us know how it goes, and feel free to post any photos etc to the Wikihouse Community Slack group.

**Comment by skovholt** [comment]
Hi @claytonprest,

thanks for your swift reply. 

1.  Just downloaded from repository now, and it seems I mistakenly might have moved some points around in my local dxf, it seems right now. Sorry about that.

Another thing regarding offsets; in the dxf for studio (Studio_1.dxf), there was a note on offsets, which read "0.25mm inset outer edges inwards (making piece smaller)". So the offset on all outer pieces in Microhouse_WRENchassis_v0.5.dxf is applied as 0.75mm? Also in Studio_1.dxf: "1mm offset inner slot holes" Are those also adjusted in Microhouse_WRENchassis_v0.5.dxf?

2. Great, thanks for clarifying. 
 
3. Excellent. 

Initially we will just build parts of a chassis, we might clad it at a later time. Also in this first run we won't make the end wall, so then we might be able to use the new system for gable and end wall when they are updated.

Joined the slack group now, and will keep you updated with some pictures when we get to that stage.

**Comment by claytonprest** [comment]
@skovholt No problem, good to have that sorted. You're right that the inset on outer edges should be 0.25mm as a general rule of thumb, but you've spotted a small anomaly at the dovetail joint locations in the F parts which already have a slight tolerance between each part. 

This is small unnecessary gap and shouldn't make much difference if you removed it. But it's always worth test cutting a few pieces with your chosen material to ensure everything is fitting tightly, and not too tight that you can't easily mallet together! You can then adjust the cutting files to suit before doing a full production run.

**Comment by skovholt** [comment]
@claytonprest Noted, thanks!
